### ISSUE TITLE
arm64 images missing for recent release

### ISSUE THREAD

**Issue by pat-s** [editorconfig-checker/editorconfig-checker#278]
https://hub.docker.com/r/mstruebing/editorconfig-checker/tags

The last one with arm64 support was 2.4.0

**Comment by 6543** [comment]
is blocking e.g. https://github.com/woodpecker-ci/woodpecker/pull/2232

**Comment by 6543** [comment]
created an workaround: https://codeberg.org/6543/docker-images/pulls/13 witch release `codeberg.org/6543/docker-images/editorconfig-checker`  
and #279 would speedup the pipeline there as also here :)

**Comment by 6543** [comment]
https://github.com/editorconfig-checker/editorconfig-checker/actions/runs/5920907572/job/16062745256 shows that the docker hub auth is failing :/

cc @mstruebing ?

**Comment by mstruebing** [comment]
I think it's because it was triggered from your branch.

I've created a new release and it works in there:
* https://hub.docker.com/layers/mstruebing/editorconfig-checker/latest/images/sha256-1b0ac79f457ab414f96b6559e8b5b2ed5bbbc7473c26b58617227c1516c21bdb?context=explore
* https://hub.docker.com/layers/mstruebing/editorconfig-checker/2.7.1/images/sha256-1b0ac79f457ab414f96b6559e8b5b2ed5bbbc7473c26b58617227c1516c21bdb?context=explore
* https://github.com/editorconfig-checker/editorconfig-checker/releases/new

I'll go ahead and close this issue.
If this issue still persists feel free to reopen with additional information.
