### ISSUE TITLE
Support include as whitelist, instead of exclude as blacklist

### ISSUE THREAD

**Issue by sanmai-NL** [editorconfig-checker/editorconfig-checker#49]

**Comment by mstruebing** [comment]
Hey, thanks for sharing your thoughts.
My understanding of this issue is: You have a file which isn't in your version control but you want to check if it is valid. Why would you want to do that?

The other way would be: you have a file inside a blacklisted directory structure, I think it shouldn't be to hard to find a fitting regular expression to exclude that single file from the blacklisting, isn't it?

Or is there any other use case I don't see?

**Comment by sanmai-NL** [comment]
I have very complicated list of files and directories to ignore, so I'd rather limit the check to a whitelist of files. And no, .gitignore isn't being respected (in my Linux-based CI environment).

**Comment by mstruebing** [comment]
Do you run the tool from the root of the git repository or from somewhere else?

**Comment by mstruebing** [comment]
I'll close this issue for now.
If you have additional thoughts or something else, feel free to add your comment or reopen this issue.

**Comment by kgryte** [comment]
For my use case, I would like to explicitly provide the checker a list of filenames to check. For example, I am looking to ensure that all files modified in a pull request conform to the project's EditorConfig.

However, currently, this requires workarounds like copying all modified files to a temporary directory and then running this tool there. Otherwise, instead of `10` files, the tool checks all files, which could be in the tens of thousands as in our project.

Personally, I'd find it more beneficial to be able to explicitly provide filenames as command-line arguments than to allow inclusion (whitelist) filters.
